---
- hosts: localhost
  ignore_errors: true
  become: true
  tasks:
    - name: Install Kubectl
      shell: |
             curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
             install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
             chmod +x /usr/local/bin/kubectl

    - name: create .kube directory               
      file:       
        path: /home/sysadmin/.kube               
        state: directory                         
        mode: 0755

- hosts: masters
  gather_facts: yes
  become: true
  tasks:
    - name: copies admin.conf to user's kube config
      fetch:                   
        src: /etc/kubernetes/admin.conf    
        dest: /home/sysadmin/.kube/config
        flat: yes
