---
- name: Deploy Kubernetes using Ansible 
  hosts: hosts
  become: true
  ignore_errors: true
  tasks:
          - name: Load br_netfilter module
            copy:
              content: | 
                    br_netfilter
                    overlay
              dest: /etc/modules-load.d/k8s.conf

          - name: Lad the modules
            shell: |
                   modprobe overlay
                   modprobe br_netfilter

          - name: load net.bridge.bridge-nf-iptables
            copy:
              content: |
                 net.bridge.bridge-nf-call-ip6tables = 1
                 net.bridge.bridge-nf-call-iptables = 1
              dest: /etc/sysctl.d/k8s.conf

          - name : Apply settings
            shell: sysctl --system

          - name: Disable Swap
            shell: |
                   swapoff -a
                   sed -i '/swap/d' /etc/fstab 
    
          - name: Install prerequites
            apt:
             name: "{{ item }}"
             state: latest
             update_cache: yes
            loop:
             - apt-transport-https
             - curl
             - ca-certificates
             - docker.io
       
          - name: Enable and start Docker
            systemd:
             name: docker
             enabled: yes
             state: started

          - name: Fix systemd cgroup driver with docker.
            shell: |
                sed -i "s|ExecStart=.*|ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --exec-opt native.cgroupdriver=systemd|g" /usr/lib/systemd/system/docker.service
                systemctl daemon-reload
                systemctl restart docker

          - name: Add google cloud public signing key
            apt_key:
               url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
               keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
          - name: Add the kubernetes apt Repository
            apt_repository:
               repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
               state: present
               filename: kubernetes
          - name: Unhold Packages
            shell: apt-mark unhold {{ item }}
            loop:
             - kubeadm
             - kubelet
             - kubectl
          - name: Install kubelet,kubeadm abd kubectl
            apt:
             pkg:
              - kubelet
              - kubeadm
              - kubectl
             update_cache: yes
          - name: hold packages
            dpkg_selections:
             name: "{{ item }}"
             selection: hold
            loop:
             - kubeadm
             - kubelet
             - kubectl  
