---
- hosts: masters
  ignore_errors: true
  tasks:
    - name: initialize the cluster
      shell: |
             kubeadm reset -f
             kubeadm init --pod-network-cidr=10.244.0.0/16 
      args:
        chdir: /root
        creates: cluster_initialized.txt

    - name: create .kube directory for sysadmin user
      file:
        path: /home/sysadmin/.kube
        state: directory
        mode: '0755'
        owner: sysadmin
        group: sysadmin
    
    - name: create .kube directory               
      file:       
        path: /root/.kube               
        state: directory                         
        mode: '0755'

    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/sysadmin/.kube/config
        mode: 0400
        owner: sysadmin
        group: sysadmin
        remote_src: yes

    - name: copies admin.conf to root kube config
      copy:                                      
        src: /etc/kubernetes/admin.conf          
        dest: /root/.kube/config       
        mode: 0400 
        remote_src: yes
      tags:
       - root_config_file

    - name: install Pod network
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

    - name: Get the token for joining the worker nodes
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command
 
    - name: join command
      set_fact:
       kubernetes_join_command: "{{ kubernetes_join_command.stdout_lines[0] }}" 
      register: kubernetes_join_command
   
    - name: Run debug on set_fact 
      debug: var=kubernetes_join_command
    
    - name: Store join command
      action: copy content="{{ kubernetes_join_command }}" dest="/tmp/kubernetes_join_command"

    - name: Fetch file from the master to controller
      fetch:
       src: /tmp/kubernetes_join_command
       dest: /tmp/kubernetes_join_command
       flat: yes

    - name: Add helm key
      apt_key:
        url: https://baltocdn.com/helm/signing.asc
        state: present
        
    - name: Add helm repository
      apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian/ all main
        state: present
        filename: helm

    - name: Install Helm and python3-pip
      apt:
       pkg:
        - helm
        - python3-pip
       update_cache: yes
      tags:
        - helm_install

    - name: Install python3-pip modules for helm
      pip:
       name: 
        - pyhelm
        - grpcio
    
    - name: Install Nginx Ingress( Kubernetes supported)
      shell: |
             helm upgrade --install ingress-nginx ingress-nginx \
             --repo https://kubernetes.github.io/ingress-nginx \
             --namespace ingress-nginx --create-namespace
      tags:
       - nginx
 
    - name: copy values.yml file to master
      copy:
       src: values.yml
       dest: /home/sysadmin
      tags:
       - copy_values

    - name: Install metallb 
      shell: |
             helm repo add metallb https://metallb.github.io/metallb
             helm repo update
             helm install metallb metallb/metallb -f values.yml
      tags:
       - metal-lb

- hosts: workers
  gather_facts: yes
  become: true
  tasks:
    - name: Copy join command from Ansiblehost to the worker nodes.
      copy:
       src: /tmp/kubernetes_join_command
       dest: /tmp/kubernetes_join_command

    - name: Run join command 
      shell: |
            chmod +x /tmp/kubernetes_join_command
             /tmp/kubernetes_join_command

